AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: pg23-cloudformation-role
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
        
      Path: /
      Policies:
        - PolicyName: CloudFormationRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - cloudwatch:*
                  - logs:*
                  - s3:*
                  - iam:*
                  - codepipeline:*
                  - ecr:*
                  - SNS:*
                  - lambda:*
                  - apigateway:*
                  - cloudformation:*
                  - codedeploy:*
                Effect: Allow
                Resource: '*' 