AWSTemplateFormatVersion: 2010-09-09

Parameters:
  RepositoryName:
    Type: String
Resources:
  pg23repo:
    Type: "AWS::CodeCommit::Repository"
    Properties:
      RepositoryDescription: "CodeCommit repository for project"
      RepositoryName: !Ref RepositoryName